package entity;
// Generated Nov 1, 2017 7:58:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories{


     private int id;
     private String nameVn;
     private String name;
     private Set<Products> productses = new HashSet<Products>(0);

    public Categories() {
    }

	
    public Categories(int id, String nameVn, String name) {
        this.id = id;
        this.nameVn = nameVn;
        this.name = name;
    }
    public Categories(int id, String nameVn, String name, Set<Products> productses) {
       this.id = id;
       this.nameVn = nameVn;
       this.name = name;
       this.productses = productses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNameVn() {
        return this.nameVn;
    }
    
    public void setNameVn(String nameVn) {
        this.nameVn = nameVn;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


