package entity;
// Generated Nov 1, 2017 7:58:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customers generated by hbm2java
 */
public class Customers {


     private String id;
     private String password;
     private String fullname;
     private String email;
     private String photo;
     private Set<Orders> orderses = new HashSet<Orders>(0);

    public Customers() {
    }

	
    public Customers(String id, String password, String fullname, String email, String photo) {
        this.id = id;
        this.password = password;
        this.fullname = fullname;
        this.email = email;
        this.photo = photo;
    }
    public Customers(String id, String password, String fullname, String email, String photo, Set<Orders> orderses) {
       this.id = id;
       this.password = password;
       this.fullname = fullname;
       this.email = email;
       this.photo = photo;
       this.orderses = orderses;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }




}


