package entity;
// Generated Nov 1, 2017 7:58:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders {


     private int id;
     private Customers customers;
     private Date orderDate;
     private Date requireDate;
     private String receiver;
     private String address;
     private String description;
     private double amount;
     private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

    public Orders() {
    }

	
    public Orders(int id, Customers customers, Date orderDate, Date requireDate, String receiver, String address, double amount) {
        this.id = id;
        this.customers = customers;
        this.orderDate = orderDate;
        this.requireDate = requireDate;
        this.receiver = receiver;
        this.address = address;
        this.amount = amount;
    }
    public Orders(int id, Customers customers, Date orderDate, Date requireDate, String receiver, String address, String description, double amount, Set<OrderDetails> orderDetailses) {
       this.id = id;
       this.customers = customers;
       this.orderDate = orderDate;
       this.requireDate = requireDate;
       this.receiver = receiver;
       this.address = address;
       this.description = description;
       this.amount = amount;
       this.orderDetailses = orderDetailses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public Date getRequireDate() {
        return this.requireDate;
    }
    
    public void setRequireDate(Date requireDate) {
        this.requireDate = requireDate;
    }
    public String getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    public Set<OrderDetails> getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
        this.orderDetailses = orderDetailses;
    }




}


